import classes
import random

print("Welcome to protgramming Priciples Sample Product Inventory")
code = input("Please enter the Product Code Number between 100 to 1000 ")
name = input("Please enter the Product Name ")
stock = input("Please enter the Current Stock ")
saleprice = input("Please enter the Product Sale Price ")
cost = input("Please enter the Product Manufacture Cost ")
units = input("Please enter estimated monthly Units production ")

productinfo = classes.product(code, name, saleprice, cost, stock, units)
print()

print("********Programming Principles Sample Stock Statement********", "\n")

print("Product Code:", int(productinfo._code))
print("Product Name:", productinfo._name, "\n")

print("Sale Price:", int(productinfo._saleprice), "CAD")
print("Manufacture Cost:", int(productinfo._cost), "CAD")
print("Monthly Production:", int(productinfo._units), "units" "(Approx)")


monthly_flucuation = str(random.randrange(-10, 11))

monthlyProd = str(productinfo._units + monthly_flucuation)
stockLeft = str(productinfo._stock + monthly_flucuation)
netProfit = (int(monthlyProd)) * (int(productinfo._saleprice)) - \
    (int(productinfo._stock) * int(productinfo._cost))


print("Month 1:")
print("Manufactured:", productinfo._units)
print("Sold:", monthlyProd)
print("Stock:", stockLeft)
print()
print("Month 2:")
print("Manufactured:", productinfo._units)
print("Sold:", monthlyProd)
print("Stock:", stockLeft)
print()
print("Month 3:")
print("Manufactured:", productinfo._units)
print("Sold:", monthlyProd)
print("Stock:", stockLeft)
print()
print("Month 4:")
print("Manufactured:", productinfo._units)
print("Sold:", monthlyProd)
print("Stock:", stockLeft)
print()
print("Month 5:")
print("Manufactured:", productinfo._units)
print("Sold:", monthlyProd)
print("Stock:", stockLeft)
print()
print("Month 6:")
print("Manufactured:", productinfo._units)
print("Sold:", monthlyProd)
print("Stock:", stockLeft)
print()
print("Month 7:")
print("Manufactured:", productinfo._units)
print("Sold:", monthlyProd)
print("Stock:", stockLeft)
print()
print("Month 8:")
print("Manufactured:", productinfo._units)
print("Sold:", monthlyProd)
print("Stock:", stockLeft)
print()
print("Month 9:")
print("Manufactured:", productinfo._units)
print("Sold:", monthlyProd)
print("Stock:", stockLeft)
print()
print("Month 10:")
print("Manufactured:", productinfo._units)
print("Sold:", monthlyProd)
print("Stock:", stockLeft)
print()
print("Month 11:")
print("Manufactured:", productinfo._units)
print("Sold:", monthlyProd)
print("Stock:", stockLeft)
print()
print("Month 12:")
print("Manufactured:", productinfo._units)
print("Sold:", monthlyProd)
print("Stock:", stockLeft)
print()
print("Net Profit:", netProfit, "CAD")
